apiVersion: v1
kind: Service
metadata:
  name: backend-service  # اسم سرویس خیلی مهمه (مثل دامنه عمل میکنه)
spec:
  type: ClusterIP        # (اختیاری) اگه ننویسیم هم همین میشه
  selector:
    app: node-app        # وصلش می‌کنیم به همون پادهای نود جی‌اس قسمت ۶
  ports:
    - port: 80           # پورت سرویس (داخل کلاستر)
      targetPort: 3000   # پورت کانتینر
